import * as cheerio from 'cheerio';
const norm=s=>(s||'').replace(/\\u003e/gi,'').replace(/\s+/g,' ').trim();
const uniq=a=>[...new Set(a.filter(Boolean))];
const blockedHosts=new Set(['mahally.com','www.mahally.com','instagram.com','www.instagram.com','twitter.com','www.twitter.com','x.com','www.x.com','tiktok.com','www.tiktok.com','snapchat.com','www.snapchat.com','facebook.com','www.facebook.com','youtube.com','www.youtube.com']);
const emailRx=/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/ig;
const phoneRx=/(?:\+?966|00966|0)?5\d{8}/g;
const phone=s=>{const x=(s||'').replace(/[^\d+]/g,'');if(/^05\d{8}$/.test(x))return'+966'+x.slice(1);if(/^009665\d{8}$/.test(x))return'+'+x.slice(2);if(/^9665\d{8}$/.test(x))return'+'+x;if(/^\+9665\d{8}$/.test(x))return x;return null};
const host=u=>{try{return new URL(u).hostname.toLowerCase()}catch{return''}};
const cleanUrl=(h,base)=>{try{const u=new URL(h,base);u.hash='';return u.href}catch{return''}};
const isExternalStoreCandidate=(u,base)=>{const h=host(u),b=host(base);return h&&h!==b&&!blockedHosts.has(h)&&!h.endsWith('.mahally.com')&&!/^(mailto:|tel:|javascript:)/i.test(u)};
export function extractMahally(html,url){const $=cheerio.load(html);const title=norm($('h1').first().text()||$('meta[property="og:title"]').attr('content')||$('title').text()).replace(/\s*[-|].*$/,'');const candidates=[];$('a[href]').each((_,e)=>{const href=cleanUrl($(e).attr('href'),url);if(!href||!isExternalStoreCandidate(href,url))return;const label=norm($(e).text()+' '+($(e).attr('aria-label')||''));let score=1;if(/زيارة|المتجر|store|shop|website|الموقع/i.test(label))score+=8;if(/salla\.sa|\.salla\./i.test(host(href)))score+=10;if($('main').find(e).length)score+=2;candidates.push({url:href,score});});candidates.sort((a,b)=>b.score-a.score);return{store_name:title,store_url:candidates[0]?.url||'',resolver_candidates:uniq(candidates.map(x=>x.url)).slice(0,10)};}
export function extractStore(html,url){const $=cheerio.load(html),text=norm($.root().text());const title=norm($('meta[property="og:site_name"]').attr('content')||$('h1').first().text()||$('title').text()).replace(/\s*[-|].*$/,'');const emails=uniq([...$('a[href^="mailto:"]').map((_,e)=>(($(e).attr('href')||'').slice(7).split('?')[0])).get(),...(text.match(emailRx)||[])]).map(x=>norm(x).toLowerCase()).filter(x=>!x.includes('mahally'));const phones=uniq([...$('a[href^="tel:"]').map((_,e)=>(($(e).attr('href')||'').slice(4))).get(),...$('a[href*="wa.me/"]').map((_,e)=>((($(e).attr('href')||'').match(/wa\.me\/(\d+)/)||[])[1])).get(),...$('a[href*="api.whatsapp.com"]').map((_,e)=>{try{return new URL($(e).attr('href')).searchParams.get('phone')}catch{return''}}).get(),...(text.match(phoneRx)||[])]).map(phone).filter(Boolean);const social={instagram:'',x:'',tiktok:'',snapchat:''};$('a[href]').each((_,e)=>{const h=cleanUrl($(e).attr('href'),url);if(!h)return;if(/instagram\.com/i.test(h))social.instagram=h;else if(/(?:twitter|x)\.com/i.test(h))social.x=h;else if(/tiktok\.com/i.test(h))social.tiktok=h;else if(/snapchat\.com/i.test(h))social.snapchat=h});const category=norm($('[class*="breadcrumb"] a').last().text()||$('meta[property="product:category"]').attr('content')||'');return{store_name:title,store_url:url,category,phone_whatsapp:phones.join(' | '),email:emails.join(' | '),...social};}
export function strongClosedEvidence(html){const $=cheerio.load(html);const title=norm($('title').text());const h1=norm($('h1').first().text());const body=norm($('body').text());return /^(?:المتجر )?(?:مغلق|تحت الصيانة)|^(?:closed|maintenance)/i.test(h1)||/المتجر مغلق|المتجر تحت الصيانة|store is closed|store under maintenance/i.test(title)||(/سنعود قريب[اًًا]?/i.test(body)&&body.length<5000);}
export const absolute=(href,base)=>{try{return new URL(href,base).href.split('#')[0]}catch{return null}};
