import {Worker,UnrecoverableError} from 'bullmq'; import * as cheerio from 'cheerio'; import {connection,discoveryQueue,enrichQueue} from './queues.js'; import {cfg} from './config.js'; import {fetcher,FetchError} from './fetcher.js'; import {absolute,extractMahally,verifyMerchantPage,extractStore,strongClosedEvidence} from './extract.js'; import {upsertStore,getRun,reserveStore} from './db.js'; import {safeJobId} from './job-id.js';
const storeHint=/\/stores\/\d+\/?$/i,bad=/\/(login|account|cart|checkout|privacy|terms)\b/i;
const permanent=k=>['robots','forbidden','http_error','dns'].includes(k);
function failPermanent(msg){throw new UnrecoverableError(msg)}
const discoveryWorker=new Worker('discovery',async job=>{const {url,depth=0,runId}=job.data;console.log(`[discovery:start] job=${job.id} run=${runId} depth=${depth} url=${url}`);const run=await getRun(runId);if(!run||run.status!=='running'){console.log(`[discovery:stop] job=${job.id} reason=run_${run?.status||'missing'}`);return{stopped:true};}let res;try{res=await fetcher.get(url,'discovery_fetch')}catch(e){console.warn(`[discovery:error] job=${job.id} kind=${e.kind||'unknown'} message=${e.message}`);throw e}if(!res.text){console.warn(`[discovery:no_content] job=${job.id} kind=${res.kind||'unknown'} status=${res.status||0}`);if(permanent(res.kind))failPermanent(`${res.kind}: ${url}`);throw new Error(`${res.kind||'fetch_failed'} HTTP ${res.status||0}`)}const $=cheerio.load(res.text);const links=[];$('a[href]').each((_,el)=>{const u=absolute($(el).attr('href'),res.url);if(!u)return;let p;try{p=new URL(u)}catch{return}if(cfg.discoveryHosts.has(p.hostname)&&storeHint.test(p.pathname))links.push({store:u.replace(/\?.*$/,''),hint:($(el).text()||'').trim()});if(depth<8&&cfg.discoveryHosts.has(p.hostname)&&!bad.test(p.pathname)&&(/page=\d+/i.test(p.search)||/\/(stores|categories|search|ar)\b/i.test(p.pathname)))links.push({page:u});});let stores=0,pages=0;for(const x of links){const current=await getRun(runId);if(!current||current.status!=='running')break;if(x.store){const reserved=await reserveStore(runId,{mahally_url:x.store,store_name:x.hint});if(!reserved.allowed)break;if(reserved.inserted){stores++;await enrichQueue.add('enrich',{mahally_url:x.store,hint:x.hint,runId},{jobId:safeJobId(`enrich-${runId}`,x.store),attempts:3,backoff:{type:'exponential',delay:3000},removeOnComplete:1000});}}else{pages++;await discoveryQueue.add('discover',{url:x.page,depth:depth+1,runId},{jobId:safeJobId(`discover-${runId}`,x.page),attempts:3,backoff:{type:'exponential',delay:3000},removeOnComplete:1000});}}console.log(`[discovery:done] job=${job.id} links=${links.length} newStores=${stores} pages=${pages}`);return{links:links.length,newStores:stores,pages};},{connection,concurrency:1});
const enrichWorker=new Worker('enrich',async job=>{const {mahally_url,hint}=job.data;const started=Date.now();console.log(`[enrich:start] job=${job.id} attempt=${job.attemptsMade+1} mahally=${mahally_url}`);try{let first;try{first=await fetcher.get(mahally_url,'mahally_fetch')}catch(e){console.warn(`[enrich:mahally_error] job=${job.id} kind=${e.kind||'unknown'} message=${e.message}`);throw e}if(!first.text){await upsertStore({mahally_url,store_name:hint,status:'mahally_unreachable',last_error:`${first.kind||'HTTP'} ${first.status||0}`});if(permanent(first.kind))failPermanent(`${first.kind}: ${mahally_url}`);throw new Error(`${first.kind||'mahally_fetch_failed'} ${first.status||0}`)}
 const meta=extractMahally(first.text,first.url);console.log(`[resolver:candidates] job=${job.id} store=${meta.store_name||hint||''} count=${meta.resolver_candidates.length}`);
 let chosen=null,lastReason='no_external_store_url';
 for(const candidate of meta.resolver_candidates){console.log(`[resolver:verify] job=${job.id} candidate=${candidate}`);let probe;try{probe=await fetcher.get(candidate,'candidate_fetch')}catch(e){lastReason=`${e.kind||'network'}:${candidate}`;console.warn(`[resolver:reject] job=${job.id} candidate=${candidate} reason=${e.kind||'network'}`);continue}if(!probe.text){lastReason=`${probe.kind||'empty'}:${candidate}`;console.warn(`[resolver:reject] job=${job.id} candidate=${candidate} reason=${probe.kind||'empty'}`);continue}const verified=verifyMerchantPage(probe.text,probe.url,meta.store_name||hint||'');if(!verified.ok){lastReason=verified.reason;console.log(`[resolver:reject] job=${job.id} candidate=${probe.url} reason=${verified.reason}`);continue}chosen={res:probe,verified};console.log(`[resolver:accept] job=${job.id} candidate=${probe.url} reason=${verified.reason}`);break;}
 if(!chosen){await upsertStore({mahally_url,store_name:meta.store_name||hint,store_url:'',status:'mahally_only',last_error:`resolver:${lastReason}`,contact_source:''});console.log(`[enrich:done] job=${job.id} status=mahally_only reason=${lastReason} duration=${Date.now()-started}ms`);return{status:'mahally_only',reason:lastReason};}
 const second=chosen.res;const data=extractStore(second.text,second.url);const status=strongClosedEvidence(second.text)?'closed_or_maintenance':'reachable';try{await upsertStore({mahally_url,store_name:data.store_name||meta.store_name||hint,store_url:second.url,category:data.category,phone_whatsapp:data.phone_whatsapp,email:data.email,instagram:data.instagram,x:data.x,tiktok:data.tiktok,snapchat:data.snapchat,status,contact_source:new URL(second.url).hostname,last_error:''});}catch(e){if(e?.code==='23505'){console.warn(`[resolver:reject] job=${job.id} candidate=${second.url} reason=store_url_already_owned`);await upsertStore({mahally_url,store_name:meta.store_name||hint,store_url:'',status:'mahally_only',last_error:'resolver:store_url_already_owned',contact_source:''});return{status:'mahally_only',reason:'store_url_already_owned'};}throw e;}
 console.log(`[enrich:done] job=${job.id} status=${status} phone=${data.phone_whatsapp?1:0} email=${data.email?1:0} duration=${Date.now()-started}ms url=${second.url}`);return{status};}catch(e){if(e?.name==='UnrecoverableError')throw e;console.warn(`[enrich:retry] job=${job.id} attempt=${job.attemptsMade+1} kind=${e.kind||'unknown'} message=${e.message}`);throw e;}},{connection,concurrency:cfg.concurrency});
for(const [name,w] of [['discovery',discoveryWorker],['enrich',enrichWorker]]){w.on('failed',(job,e)=>console.error(`[${name}:failed] job=${job?.id||'unknown'} attemptsMade=${job?.attemptsMade||0} message=${e.message}`));w.on('error',e=>console.error(`[${name}:worker_error] ${e.stack||e}`));}
console.log(`[worker] discovery concurrency=1; enrich concurrency=${cfg.concurrency}; requestTimeoutMs=${cfg.requestTimeoutMs}; delayMs=${cfg.delay}`);
